HikeLog.WebMVC/Controllers/DailyLogController.cs
using HikeLog.Models.DailyLog;
using HikeLog.Services;
using Microsoft.AspNet.Identity;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace HikeLog.WebMVC.Controllers
{
    public class DailyLogController : Controller
    {
        [Authorize]

        // GET: DailyLog
        public ActionResult Index(string option, string search)
        {
            var service = CreateDailyLogService();
            if(option == "Section")
            {
                var model = service.GetDailyLogBySection(search);
                return View(model);
            }
            else if(option == "Miles Hiked")
            {
                var model = service.GetDailyLogByMilesHiked(search);
                return View(model);
            }
            else if (option == "Date")
            {
                var model = service.GetDailyLogByDate(search);
                return View(model);
            }
            else if (option == "Mile Marker")
            {
                var model = service.GetDailyLogByMileMarker(search);
                return View(model);
            }
            else if (option == "Has Notes")
            {
                var model = service.GetDailyLogByHasNotes(search);
                return View(model);
            }
            else if (option == "Note Content")
            {
                var model = service.GetDailyLogByNoteContent(search);
                return View(model);
            }
            else if (option == "Starred")
            {
                var model = service.GetDailyLogByStarStatus(search);
                return View(model);
            }
            else
            {
                var model = service.GetDailyLogs();
                            return View(model);
            }
            
        }

        // GET : DailyLog
        public ActionResult Create()
        {
            ViewBag.Title = "New DailyLog";
            return View();
        }

        // POST : DailyLog
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(DailyLogCreate model)
        {
            if (!ModelState.IsValid) return View(model);

            var service = CreateDailyLogService();

            if (service.CreateDailyLog(model))
            {
                TempData["SaveResult"] = "Your DailyLog was created!";
                return RedirectToAction("Index");
            };

            ModelState.AddModelError("", "DailyLog could not be created.");
            return View(model);
        }

        public ActionResult Details(int id)
        {
            var svc = CreateDailyLogService();
            var model = svc.GetDailyLogById(id);

            return View(model);
        }

        public ActionResult Edit(int id)
        {
            var service = CreateDailyLogService();
            var detail = service.GetDailyLogById(id);
            var model =
                new DailyLogEdit
                {
                    DailyLogId = detail.DailyLogId,
                    ProfileId = detail.ProfileId,
                    SectionId = detail.SectionId,
                    Date = detail.Date,
                    StartMile = detail.StartMile,
                    EndMile = detail.EndMile,
                    Notes = detail.Notes,
                    IsStarred = detail.IsStarred

                };
            return View(model);
        }

       [HttpPost]
       [ValidateAntiForgeryToken]

       public ActionResult Edit(int id, DailyLogEdit model)
        {
            if (!ModelState.IsValid) return View(model);
            if(model.DailyLogId != id)
            {
                ModelState.AddModelError("", "Id Mismatch");
                return View(model);
            }

            var service = CreateDailyLogService();

            if (service.UpdateDailyLog(model))
            {
                TempData["SaveResult"] = "Your DailyLog was updated.";
                return RedirectToAction("Index");
            }

            ModelState.AddModelError("", "Your DailyLog could not be updated.");
            return View(model);
        }

        [ActionName("Delete")]
        public ActionResult Delete(int id)
        {
            var svc = CreateDailyLogService();
            var model = svc.GetDailyLogById(id);

            return View(model);
        }

        [HttpPost]
        [ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeletePost(int id)
        {
            var service = CreateDailyLogService();
            service.DeleteDailyLog(id);
            TempData["SaveResult"] = "Your DailyLog was deleted";
            return RedirectToAction("Index");
        }


        private DailyLogService CreateDailyLogService()
        {
            var userId = Guid.Parse(User.Identity.GetUserId());
            var service = new DailyLogService(userId);
            return service;
        }
    }
}

HikeLog.WebMVC/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace HikeLog.WebMVC.Controllers
{
    public class HomeController : Controller
    {
        public ActionResult Index()
        {
            return View();
        }

        public ActionResult About()
        {
            ViewBag.Message = "Your application description page.";

            return View();
        }

        public ActionResult Contact()
        {
            ViewBag.Message = "Your contact page.";

            return View();
        }
    }
}

HikeLog.WebMVC/Controllers/SectionController.cs
using HikeLog.Models;
using HikeLog.Models.Section;
using HikeLog.Services;
using Microsoft.AspNet.Identity;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace HikeLog.WebMVC.Controllers
{
    [Authorize]
    public class SectionController : Controller
    {
        // GET: Section
        public ActionResult Index(string option, string search)
        {
            var service = CreateSectionService();
            if (option == "Name")
            {
                var model = service.GetSectionByName(search);
                return View(model);
            }
            else if (option == "Direction")
            {
                var model = service.GetSectionByDirection(search);
                return View(model);
            }
            else if (option == "Date")
            {
                var model = service.GetSectionByDate(search);
                return View(model);
            }
            else if (option == "Mile Marker")
            {
                var model = service.GetSectionByMM(search);
                return View(model);
            }
            else
            {
                var model = service.GetSections();
                return View(model);
            }
        }

        // GET : Section
        public ActionResult Create()
        {
            ViewBag.Title = "New Section";
            return View();
        }

        // POST : Section
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(SectionCreate model)
        {
            if (!ModelState.IsValid) return View(model);
            
            var service = CreateSectionService();

            if (service.CreateSection(model))
            {
                TempData["SaveResult"] = "Your Section was created!";
                return RedirectToAction("Index");
            };

            ModelState.AddModelError("", "Section could not be created.");
            return View(model);
        }

        public ActionResult Details(int id)
        {
            var svc = CreateSectionService();
            var model = svc.GetSectionById(id);

            return View(model);
        }
                
        public ActionResult Edit(int id)
        {
            var service = CreateSectionService();
            var detail = service.GetSectionById(id);
            var model =
                new SectionEdit
                {
                    SectionId = detail.SectionId,
                    SectionName = detail.SectionName,
                    StartDate = detail.StartDate,
                    EndDate = detail.EndDate,
                    StartMile = detail.StartMile,
                    EndMile = detail.EndMile,
                    Direction = detail.Direction
                };
            return View(model);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(int id, SectionEdit model)
        {
            if (!ModelState.IsValid) return View(model);
            if(model.SectionId != id)
            {
                ModelState.AddModelError("", "Id Mismatch");
                return View(model);
            }

            var service = CreateSectionService();

            if (service.UpdateSection(model))
            {
                TempData["SaveResult"] = "Your Section was updated.";
                return RedirectToAction("Index");
            }

            ModelState.AddModelError("", "Your Section could not be updated.");
            return View(model);
        }

        [ActionName("Delete")]
        public ActionResult Delete(int id)
        {
            var svc = CreateSectionService();
            var model = svc.GetSectionById(id);

            return View(model);
        }

        [HttpPost]
        [ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeletePost(int id)
        {
            var service = CreateSectionService();
            service.DeleteSection(id);
            TempData["SaveResult"] = "Your Section was deleted";
            return RedirectToAction("Index");
        }

        private SectionService CreateSectionService()
        {
            var userId = Guid.Parse(User.Identity.GetUserId());
            var service = new SectionService(userId);
            return service;
        }
    }

    
}

HikeLog.WebMVC/Controllers/StatisticsController.cs
using HikeLog.Services;
using Microsoft.AspNet.Identity;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace HikeLog.WebMVC.Controllers
{
    public class StatisticsController : Controller
    {
        [Authorize]
        // GET: Statistics
                
        public ActionResult Details(string option, string sectionId)
        {
            int section = Convert.ToInt32(sectionId);
            var svc = CreateStatisticsService();
            if(option == "Section")
            {
                var model = svc.GetStatsForSection(section);
                return View(model);
            }
            return View();
        }

        private StatisticsService CreateStatisticsService()
        {
            var userId = Guid.Parse(User.Identity.GetUserId());
            var service = new StatisticsService(userId);
            return service;
        }
    }

    
}

HikeLog.WebMVC/Views/Home/About.cshtml
@{
    ViewBag.Title = "About";
}
<h2>@ViewBag.Title</h2>
<h3>Origins of AT Hike Log</h3>

<p>The idea for this app came about as a result of my 2021 AT section hike from Springer Mtn, GA to Hot Springs, NC.</p>

<p>Every night in camp, I would pull up my Google Sheets spreadsheet and tediously type in starting and ending mile markers, compare actual progress vs 
    my plan, and try to write formulas to view average miles per day pace.  Trying to do that on a cell phone in the woods is not very easy.
    I also wrote notes in a journal by hand with a pad of paper and pen.</p>

<p>I thought it would be nice to have an app where all you have to do is key in start and ending mile markers for each days' hike,',
    perhaps add some notes, and let the app do all the heavy lifting for calculating stats.</p>

<p>At it's core this is all the app was designed to do, but over time the hope is to further develop it and add functionality that would be useful
    to other AT hikers that isn't captured in existing apps.</p>

HikeLog.WebMVC/Views/Home/Contact.cshtml
@{
    ViewBag.Title = "Contact";
}
<h2>@ViewBag.Title</h2>

<address>
    <strong>Web:</strong>   <a href="https://jderdman.com" target="_blank" rel="noopener noreferrer">jderdman.com</a><br />
    <strong>Email:</strong>   <a href="mailto:jeff@jderdman.com">jeff@jderdman.com</a><br />
    <strong>Phone:</strong>   317-721-4506<br />
    <strong>LinkedIn:</strong> <a href="https://linkedin.com/in/jderdman" target="_blank" rel="noopener noreferrer">linkedin.com/in/jderdman</a><br />
    <strong>Github:</strong> <a href="https://github.com/jerdman81" target="_blank" rel="noopener noreferrer">github.com/jerdman81</a><br />

</address>

HikeLog.WebMVC/Views/Home/Index.cshtml
@{
    ViewBag.Title = "Home Page";
}
@section head{
    <style type="text/css">
        body {
            background-image: url('/Assets/20210517_073258.jpg');
            background-size: 100% auto;
            margin: 0;
            }
        </style>
    }

    <div class="jumbotron" style="margin-top: 5rem">
        <h1>AT Hike Log</h1>
        <p class="lead">An app to simplify tracking daily miles on the AT.</p>
        @if (User.Identity.IsAuthenticated)
        {
            <button class="btn btn-primary">@Html.ActionLink("Add Log Entry", "Create", "DailyLog", null, new { id = "OT", style = "color: white" })</button>
            <br /><br />
            <button class="btn btn-primary">@Html.ActionLink("Add Section", "Create", "Section", null, new { id = "OT", style = "color: white" })</button>
            <br /><br />
            <button class="btn btn-primary">@Html.ActionLink("View Statistics", "Details", "Statistics", null, new { id = "OT", style = "color: white" })</button>
        }

        @if (!User.Identity.IsAuthenticated)
        {
            <button class="btn btn-primary">@Html.ActionLink("Log In", "Login", "Account", null, new { id = "OT", style = "color: white" })</button>

            <br /><br />
            <button class="btn btn-primary">@Html.ActionLink("Register", "Register", "Account", null, new { id = "OT", style = "color: white" })</button>
        }
    </div>