HikeLog.WebMVC/Controllers/SectionController.cs
using HikeLog.Models;
using HikeLog.Models.Section;
using HikeLog.Services;
using Microsoft.AspNet.Identity;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace HikeLog.WebMVC.Controllers
{
    [Authorize]
    public class SectionController : Controller
    {
        // GET: Section
        public ActionResult Index(string option, string search)
        {
            var service = CreateSectionService();
            if (option == "Name")
            {
                var model = service.GetSectionByName(search);
                return View(model);
            }
            else if (option == "Direction")
            {
                var model = service.GetSectionByDirection(search);
                return View(model);
            }
            else if (option == "Date")
            {
                var model = service.GetSectionByDate(search);
                return View(model);
            }
            else if (option == "Mile Marker")
            {
                var model = service.GetSectionByMM(search);
                return View(model);
            }
            else
            {
                var model = service.GetSections();
                return View(model);
            }
        }

        // GET : Section
        public ActionResult Create()
        {
            ViewBag.Title = "New Section";
            return View();
        }

        // POST : Section
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(SectionCreate model)
        {
            if (!ModelState.IsValid) return View(model);
            
            var service = CreateSectionService();

            if (service.CreateSection(model))
            {
                TempData["SaveResult"] = "Your Section was created!";
                return RedirectToAction("Index");
            };

            ModelState.AddModelError("", "Section could not be created.");
            return View(model);
        }

        public ActionResult Details(int id)
        {
            var svc = CreateSectionService();
            var model = svc.GetSectionById(id);

            return View(model);
        }
                
        public ActionResult Edit(int id)
        {
            var service = CreateSectionService();
            var detail = service.GetSectionById(id);
            var model =
                new SectionEdit
                {
                    SectionId = detail.SectionId,
                    SectionName = detail.SectionName,
                    StartDate = detail.StartDate,
                    EndDate = detail.EndDate,
                    StartMile = detail.StartMile,
                    EndMile = detail.EndMile,
                    Direction = detail.Direction
                };
            return View(model);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(int id, SectionEdit model)
        {
            if (!ModelState.IsValid) return View(model);
            if(model.SectionId != id)
            {
                ModelState.AddModelError("", "Id Mismatch");
                return View(model);
            }

            var service = CreateSectionService();

            if (service.UpdateSection(model))
            {
                TempData["SaveResult"] = "Your Section was updated.";
                return RedirectToAction("Index");
            }

            ModelState.AddModelError("", "Your Section could not be updated.");
            return View(model);
        }

        [ActionName("Delete")]
        public ActionResult Delete(int id)
        {
            var svc = CreateSectionService();
            var model = svc.GetSectionById(id);

            return View(model);
        }

        [HttpPost]
        [ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeletePost(int id)
        {
            var service = CreateSectionService();
            service.DeleteSection(id);
            TempData["SaveResult"] = "Your Section was deleted";
            return RedirectToAction("Index");
        }

        private SectionService CreateSectionService()
        {
            var userId = Guid.Parse(User.Identity.GetUserId());
            var service = new SectionService(userId);
            return service;
        }
    }

    
}

HikeLog.WebMVC/Views/Section/Create.cshtml
@model HikeLog.Models.Section.SectionCreate
@using HikeLog.Data.Enums

@{
    ViewBag.Title = "Create";
}

<h2>Create</h2>


@using (Html.BeginForm()) 
{
    @Html.AntiForgeryToken()
    
<div class="form-horizontal">
    <h4>SectionCreate</h4>
    <hr />
    @Html.ValidationSummary(true, "", new { @class = "text-danger" })
    <div class="form-group">
        @Html.LabelFor(model => model.ProfileId, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.ProfileId, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.ProfileId, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.SectionName, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.SectionName, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.SectionName, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.StartDate, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.StartDate, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.StartDate, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.EndDate, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.EndDate, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.EndDate, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.StartMile, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.StartMile, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.StartMile, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.EndMile, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.EndMile, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.EndMile, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.Direction, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.DropDownListFor(model => model.Direction, new SelectList(Enum.GetValues(typeof(HikeDirection))),"Hike Direction",new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.Direction, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        <div class="col-md-offset-2 col-md-10">
            <input type="submit" value="Create" class="btn btn-default" />
        </div>
    </div>
</div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

HikeLog.WebMVC/Views/Section/Delete.cshtml
@model HikeLog.Models.Section.SectionDetail

@{
    ViewBag.Title = "Delete";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>SectionDetail</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.SectionId)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.SectionId)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.ProfileId)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.ProfileId)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.SectionName)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.SectionName)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.StartDate)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.StartDate)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.EndDate)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.EndDate)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.StartMile)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.StartMile)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.EndMile)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.EndMile)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.Direction)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Direction)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.CreatedUtc)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.CreatedUtc)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.ModifiedUtc)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.ModifiedUtc)
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-default" /> |
            @Html.ActionLink("Back to List", "Index")
        </div>
    }
</div>

HikeLog.WebMVC/Views/Section/Details.cshtml
@model HikeLog.Models.Section.SectionDetail

@{
    ViewBag.Title = "Details";
}

<h2>Details</h2>

<div>
    <h4>SectionDetail</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.SectionId)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.SectionId)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.ProfileId)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.ProfileId)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.SectionName)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.SectionName)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.StartDate)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.StartDate)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.EndDate)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.EndDate)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.StartMile)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.StartMile)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.EndMile)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.EndMile)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.Direction)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Direction)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.CreatedUtc)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.CreatedUtc)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.ModifiedUtc)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.ModifiedUtc)
        </dd>

    </dl>
</div>
<p>
    @Html.ActionLink("Edit", "Edit", new { id = Model.SectionId }) |
    @Html.ActionLink("Back to List", "Index")
</p>

HikeLog.WebMVC/Views/Section/Edit.cshtml
@model HikeLog.Models.Section.SectionEdit
@using HikeLog.Data.Enums

@{
    ViewBag.Title = "Edit";
}

<h2>Edit</h2>


@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    
<div class="form-horizontal">
    <h4>SectionEdit</h4>
    <hr />
    @Html.ValidationSummary(true, "", new { @class = "text-danger" })
    @Html.HiddenFor(m => m.SectionId)
    
    <div class="form-group">
        @Html.LabelFor(model => model.SectionName, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.SectionName, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.SectionName, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.StartDate, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.StartDate, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.StartDate, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.EndDate, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.EndDate, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.EndDate, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.StartMile, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.StartMile, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.StartMile, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.EndMile, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.EndMile, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.EndMile, "", new { @class = "text-danger" })
        </div>
    </div>
    <div class="form-group">
        @Html.LabelFor(model => model.Direction, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.DropDownListFor(model => model.Direction, new SelectList(Enum.GetValues(typeof(HikeDirection))), "Hike Direction", new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.Direction, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        <div class="col-md-offset-2 col-md-10">
            <input type="submit" value="Save" class="btn btn-default" />
        </div>
    </div>
</div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

HikeLog.WebMVC/Views/Section/Index.cshtml
@model IEnumerable<HikeLog.Models.Section.SectionListItem>

@{
    ViewBag.Title = "Index";
}

<h2>Section Index</h2>

<p>
    @Html.ActionLink("Create New", "Create")
</p>
<p>
    @Html.ActionLink("Reset View", "Index")
</p>
@if (TempData.ContainsKey("SaveResult"))
{
    <div class="alert alert-success fade in" role="alert">
        <buton type="button" class="close" data-dismiss="alert">
            <span>&times;</span>
        </buton>
        @TempData["SaveResult"]
    </div>
}


@using (Html.BeginForm("Index", "Section", FormMethod.Get))
{
    <b> Search Option: </b>@Html.RadioButton("option", "Name") <text>Name</text> @Html.RadioButton("option", "Direction") <text>Direction</text>
    @Html.RadioButton("option", "Date") <text>Date</text> @Html.RadioButton("option", "Mile Marker") <text>Mile Marker</text>
    @Html.TextBox("search")
    <input type="submit" name="submit" value="Search" />
}
<br>
<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.SectionId)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.ProfileId)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.SectionName)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.StartDate)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.EndDate)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.StartMile)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.EndMile)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Direction)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.CreatedUtc)
        </th>
        <th></th>
    </tr>

    @if (Model.Count() == 0)
    {
        <tr> <td colspan="3"> No Records Found! </td></tr>
    }
    else
    {
        foreach (var item in Model)
        {
            <tr>
                <td>
                    @Html.DisplayFor(modelItem => item.SectionId)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.ProfileId)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.SectionName)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.StartDate)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.EndDate)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.StartMile)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.EndMile)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Direction)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.CreatedUtc)
                </td>
                <td>
                    @Html.ActionLink("Edit", "Edit", new { id = item.SectionId }) |
                    @Html.ActionLink("Details", "Details", new { id = item.SectionId }) |
                    @Html.ActionLink("Delete", "Delete", new { id = item.SectionId })
                </td>
            </tr>
        }
    }

</table>